import "bootstrap/dist/css/bootstrap.min.css";
import localFont from "next/font/local";
import "./globals.css";
import "./cart.css";


import Nav from "./components/Nav";
import { CustomProviders } from "./provider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <CustomProviders>
        <Nav/>
        {children}
        </CustomProviders>
      </body>
      <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" />
    </html>
  );
}
